[workspace]
resolver = "2"
members = [
    "crates/koma-core",
    "crates/koma-adapters/koma-epub",
    "crates/koma-adapters/koma-markdown",
    "crates/koma-analysis",
    "crates/koma-compiler",
    "crates/koma-renderer",
    "crates/koma-scene",
    "crates/koma-server",
    "crates/koma-theme",
    "crates/koma-runtime",
    "tools/koma-cli",
]

[workspace.package]
version = "0.2.0"
edition = "2024"
rust-version = "1.85"

[profile.release]
lto = "thin"
opt-level = 3