[workspace]
resolver = "2"
members = [
    "crates/koma-core",
    "crates/koma-adapters/koma-epub",
    "crates/koma-compiler",
    "crates/koma-renderer",
    "tools/koma-cli",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[profile.release]
lto = "thin"
opt-level = 3